shelf_analysis_task:
  description: >
    **Objective:** Count product faces for each brand in the provided shelf images for the **{category}** category.

    **Input Data:**
    - **Image URLs:** {images_urls} (List of shelf image URLs.)
    - **Brands JSON:** {brands} (Includes 'identifier' and 'brand_name'.)
    - **Products JSON:** {products} (Includes 'product_id', 'product_name', 'product_description', 'brand_id'.)

    **Instructions:**
    1.  **Image Processing:** Identify and count visible product faces in each image.
    2.  **Product Identification:** Use **'product_description'** from the products JSON to identify products.
    3.  **Brand Association:** Link identified products to brands using the **'brand_id'** from products JSON, matching it with the 'identifier' in the brands JSON.
    4.  **Outras Marcas:** If you identify product faces from brands not listed or uncertain, quantify them under **"Outras Marcas"**.

    **Agent Focus:** Ensure accurate face counts, correct brand association, and proper categorization of unknown brands.

  expected_output: >
    A JSON array with the total count of faces per brand. Each entry must include `brand_id`, `brand_name` and the number of `faces` found.

  agent: merchandising_promoter
